import Navbar from "@/components/ui/Navbar";
import type { Metadata } from "next";
import "./globals.css";
import { SidebarProvider, SidebarInset } from "@/components/ui/sidebar"
import { AppSidebar } from "@/components/custom/SideBar";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <SidebarProvider>
    <html lang="sv">
      <body className="overflow-x-hidden">
      <AppSidebar />
            <SidebarInset className="overflow-x-hidden">
        <Navbar />
        <main className="min-h-screen">
          {children}
        </main>
      </SidebarInset>
      </body>
    </html>
    </SidebarProvider>
  );
}
